import React from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { X, FileCheck, Download, Printer } from 'lucide-react';
import { Button } from '../ui/Button';

interface ReportPreviewModalProps {
  isOpen: boolean;
  onClose: () => void;
  onDownload: () => void;
  filename?: string;
  riskScore?: number | null;
  summary?: string;
}

export const ReportPreviewModal: React.FC<ReportPreviewModalProps> = ({
  isOpen,
  onClose,
  onDownload,
  filename = 'Contract_Analysis_Report.pdf',
  riskScore = 45,
  summary = 'Executive contract risk analysis preview.',
}) => {
  if (!isOpen) return null;

  const handlePrint = () => {
    window.print();
  };

  return (
    <AnimatePresence>
      <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-xs">
        <motion.div
          initial={{ scale: 0.95, opacity: 0 }}
          animate={{ scale: 1, opacity: 1 }}
          exit={{ scale: 0.95, opacity: 0 }}
          className="bg-white dark:bg-slate-900 rounded-2xl max-w-2xl w-full h-[80vh] shadow-2xl border border-slate-200 dark:border-slate-800 flex flex-col overflow-hidden"
        >
          {/* Header */}
          <div className="p-4 border-b border-slate-200 dark:border-slate-800 flex items-center justify-between bg-slate-50 dark:bg-slate-950">
            <div className="flex items-center gap-2.5">
              <div className="w-8 h-8 rounded-lg bg-indigo-600 text-white flex items-center justify-center">
                <FileCheck className="w-4 h-4" />
              </div>
              <div>
                <h3 className="text-sm font-bold text-slate-900 dark:text-slate-100">PDF Report Preview</h3>
                <p className="text-[11px] text-slate-500">{filename}</p>
              </div>
            </div>

            <div className="flex items-center gap-2">
              <Button variant="outline" size="xs" onClick={handlePrint} iconLeft={<Printer className="w-3.5 h-3.5" />}>
                Print
              </Button>
              <Button size="xs" onClick={onDownload} iconLeft={<Download className="w-3.5 h-3.5" />}>
                Download
              </Button>
              <Button variant="ghost" size="xs" onClick={onClose}>
                <X className="w-4 h-4" />
              </Button>
            </div>
          </div>

          {/* Printable Report Document Sheet */}
          <div className="flex-1 overflow-y-auto p-8 bg-slate-100 dark:bg-slate-950 font-sans print:p-0">
            <div className="max-w-xl mx-auto bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl p-8 shadow-lg space-y-6 text-slate-800 dark:text-slate-100">
              {/* Report Header */}
              <div className="flex items-center justify-between border-b pb-4 border-slate-200 dark:border-slate-800">
                <div>
                  <h1 className="text-xl font-black tracking-tight text-indigo-600 dark:text-indigo-400">LegalEase</h1>
                  <p className="text-[10px] text-slate-400 uppercase tracking-widest font-semibold mt-0.5">
                    Automated Contract Assessment Report
                  </p>
                </div>
                <div className="text-right">
                  <span className="text-[10px] text-slate-400 block">Date Generated</span>
                  <span className="text-xs font-semibold">{new Date().toLocaleDateString()}</span>
                </div>
              </div>

              {/* Document Overview */}
              <div className="grid grid-cols-2 gap-4 p-4 bg-slate-50 dark:bg-slate-800/50 rounded-xl text-xs">
                <div>
                  <span className="text-slate-400 text-[10px] block">Document File</span>
                  <span className="font-bold truncate block">{filename}</span>
                </div>
                <div>
                  <span className="text-slate-400 text-[10px] block">Overall Risk Rating</span>
                  <span className="font-bold text-indigo-600 dark:text-indigo-400">{riskScore ?? 0} / 100</span>
                </div>
              </div>

              {/* Summary Section */}
              <div className="space-y-2">
                <h4 className="text-xs font-bold uppercase tracking-wider text-slate-400">Analysis Summary</h4>
                <p className="text-xs leading-relaxed text-slate-600 dark:text-slate-300">{summary}</p>
              </div>

              {/* Disclaimer */}
              <div className="pt-6 border-t border-slate-100 dark:border-slate-800 text-[10px] text-slate-400 text-center italic">
                This report is generated by LegalEase AI analysis for informational purposes and does not constitute formal legal advice.
              </div>
            </div>
          </div>
        </motion.div>
      </div>
    </AnimatePresence>
  );
};
